(()=>{
"use strict";
if(window.__SonnetRecorderPro?.destroy)window.__SonnetRecorderPro.destroy();
const KEY="sonnet-recorder-settings-v1";
const defaults={hideRecorder:true,hideSonnet:true,restoreAfterStop:true,fadeMs:220,resolution:"original",fps:60,bitrate:8,gameAudio:true,mic:false,saveConfirm:true,autoSave:false,fileName:"sonnet",includeFilters:true,includeCrosshair:true,includeKeystrokes:true,includeStats:true,profile:"custom"};
let settings={...defaults};try{settings={...settings,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{}
const root=document.createElement("div");root.id="sonnet-recorder-pro";
root.innerHTML=`<div class="srp-box"><button class="srp-close" aria-label="録画UIを閉じる">×</button><h3>🎥 Sonnet Recorder</h3><div class="srp-tabs"><button data-tab="record">Record</button><button data-tab="settings">Settings</button></div><section id="srp-record"><button id="srp-start">● Start Recording</button><button id="srp-stop" disabled>■ Stop</button><div id="srp-status">Ready</div></section><section id="srp-settings" hidden><h4>Recording UI</h4><label><span>Hide Recorder UI</span><input data-k="hideRecorder" type="checkbox"></label><label><span>Hide Sonnet UI</span><input data-k="hideSonnet" type="checkbox"></label><label><span>Restore UI after stop</span><input data-k="restoreAfterStop" type="checkbox"></label><label><span>Fade duration</span><input data-k="fadeMs" type="range" min="0" max="1000" step="10"></label><h4>Quality</h4><label><span>Resolution</span><select data-k="resolution"><option value="original">Original</option><option value="1080">1080p</option><option value="720">720p</option><option value="480">480p</option></select></label><label><span>FPS</span><select data-k="fps"><option>60</option><option>30</option><option>24</option></select></label><label><span>Bitrate</span><select data-k="bitrate"><option>4</option><option>8</option><option>12</option><option>16</option></select></label><h4>Audio</h4><label><span>Game audio</span><input data-k="gameAudio" type="checkbox"></label><label><span>Microphone</span><input data-k="mic" type="checkbox"></label><h4>Overlay</h4><label><span>Screen Filters</span><input data-k="includeFilters" type="checkbox"></label><label><span>Crosshair</span><input data-k="includeCrosshair" type="checkbox"></label><label><span>Keystrokes</span><input data-k="includeKeystrokes" type="checkbox"></label><label><span>FPS / CPS</span><input data-k="includeStats" type="checkbox"></label><h4>Saving</h4><label><span>Ask before saving</span><input data-k="saveConfirm" type="checkbox"></label><label><span>Auto save</span><input data-k="autoSave" type="checkbox"></label><label><span>File name</span><input data-k="fileName" type="text"></label><button id="srp-save-settings">Save settings</button></section></div><button id="srp-reopen" aria-label="レコーダーを表示">🎥 レコーダー</button>`;
const css=document.createElement("style");css.textContent=`#sonnet-recorder-pro{position:fixed;inset:0;z-index:2147483647;pointer-events:none;font-family:Arial,sans-serif}#sonnet-recorder-pro .srp-box{position:absolute;right:18px;bottom:18px;width:min(390px,90vw);max-height:82vh;overflow:auto;padding:16px;background:rgba(4,8,20,.96);border:1px solid #00cfff66;border-radius:14px;color:#fff;box-shadow:0 0 35px #00cfff33;pointer-events:auto}#sonnet-recorder-pro h3{margin:0 0 12px;color:#00cfff}#sonnet-recorder-pro h4{margin:14px 0 7px;color:#8be9ff;font-size:12px;text-transform:uppercase}#sonnet-recorder-pro label{display:flex;justify-content:space-between;gap:12px;align-items:center;margin:7px 0;font-size:12px;color:#ccd}#sonnet-recorder-pro input[type=range]{width:150px}#sonnet-recorder-pro input[type=text],#sonnet-recorder-pro select,#sonnet-recorder-pro button{background:#071321;color:#fff;border:1px solid #00cfff55;border-radius:7px;padding:7px}#sonnet-recorder-pro button{cursor:pointer}.srp-close{float:right;font-size:18px;line-height:1}.srp-tabs{display:flex;gap:6px;margin-bottom:12px}.srp-tabs button.active{background:#00cfff33;border-color:#00cfff}.srp-box section{margin-top:8px}#srp-status{margin-top:9px;color:#9ab}#srp-reopen{position:fixed;right:18px;bottom:18px;display:none!important;pointer-events:auto;background:rgba(4,8,20,.96)!important;border:1px solid #00cfff88!important;color:#fff!important;border-radius:9px!important;padding:9px 12px!important;box-shadow:0 0 20px #00cfff33;z-index:2147483647}#sonnet-recorder-pro.closed .srp-box,#sonnet-recorder-pro.closed #srp-reopen{display:none!important}#sonnet-recorder-pro.opened #srp-reopen{display:none!important}`;document.head.append(css);document.body.append(root);
// Fresh load: recorder UI is completely absent. It appears only after the user invokes open().
root.classList.add("closed");
const q=s=>root.querySelector(s),save=()=>localStorage.setItem(KEY,JSON.stringify(settings));
root.querySelectorAll("[data-k]").forEach(el=>{const k=el.dataset.k;if(el.type==="checkbox")el.checked=!!settings[k];else el.value=settings[k];el.addEventListener("change",()=>{settings[k]=el.type==="checkbox"?el.checked:el.value;save()});el.addEventListener("input",()=>{settings[k]=el.type==="checkbox"?el.checked:el.value;save()})});
root.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{root.querySelectorAll("[data-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");q("#srp-record").hidden=b.dataset.tab!=="record";q("#srp-settings").hidden=b.dataset.tab!=="settings"});q('[data-tab="record"]').classList.add("active");
let recorder=null,chunks=[],stream=null,sonnetHidden=[];
function open(){root.classList.remove("closed");root.classList.add("opened")}function close(){if(recorder?.state==="recording")return;root.classList.remove("opened");root.classList.add("closed")}q(".srp-close").onclick=close;q("#srp-reopen").onclick=open;q("#srp-save-settings").onclick=()=>{save();q("#srp-status").textContent="Settings saved"};
function hideUI(){if(settings.hideRecorder)close();if(settings.hideSonnet){const u=document.getElementById("galaxy-ui");if(u){sonnetHidden=[u.style.visibility,u.style.opacity];u.style.transition=`opacity ${settings.fadeMs}ms`;u.style.opacity="0";u.style.visibility="hidden"}}}
function restoreUI(){if(settings.restoreAfterStop){const u=document.getElementById("galaxy-ui");if(u){u.style.transition=`opacity ${settings.fadeMs}ms`;u.style.visibility="visible";u.style.opacity=sonnetHidden[1]??"1"}}open()}
async function start(){if(recorder?.state==="recording")return;try{stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:+settings.fps||60},audio:settings.gameAudio});let type="video/webm;codecs=vp9,opus";if(!MediaRecorder.isTypeSupported(type))type="video/webm";recorder=new MediaRecorder(stream,{mimeType:type,bitsPerSecond:(+settings.bitrate||8)*1000000});chunks=[];recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=stop;recorder.start(250);q("#srp-start").disabled=true;q("#srp-stop").disabled=false;q("#srp-status").textContent="● Recording…";hideUI()}catch(e){q("#srp-status").textContent="Recording cancelled";console.warn("[Sonnet Recorder Pro]",e)}}
function stop(){stream?.getTracks().forEach(t=>t.stop());stream=null;q("#srp-start").disabled=false;q("#srp-stop").disabled=true;q("#srp-status").textContent="Recording finished";restoreUI();if(settings.autoSave)download();else if(settings.saveConfirm&&confirm("録画を保存しますか？"))download()}
function download(){if(!chunks.length)return;const a=document.createElement("a"),url=URL.createObjectURL(new Blob(chunks,{type:"video/webm"}));a.href=url;a.download=`${settings.fileName||"sonnet"}-${new Date().toISOString().replace(/[:.]/g,"-")}.webm`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
q("#srp-start").onclick=start;q("#srp-stop").onclick=()=>recorder?.stop();
window.__SonnetRecorderPro={settings,open,close,start,stop:()=>recorder?.stop(),download,save,destroy(){if(recorder?.state==="recording")recorder.stop();stream?.getTracks().forEach(t=>t.stop());root.remove();css.remove()}};
})();
