(()=>{
"use strict";
if(window.__SonnetScreenFilters?.destroy)window.__SonnetScreenFilters.destroy();
const KEY="sonnet-screen-filters-v1";
const presets={
 normal:{name:"Normal",brightness:1,contrast:1,saturation:1,hue:0,sepia:0,grayscale:0},
 night:{name:"Night Vision",brightness:1.28,contrast:1.18,saturation:1.05,hue:82,sepia:.18,grayscale:0},
 dramatic:{name:"Dramatic",brightness:.96,contrast:1.32,saturation:1.12,hue:0,sepia:.02,grayscale:0},
 vivid:{name:"Vivid",brightness:1.04,contrast:1.1,saturation:1.42,hue:0,sepia:0,grayscale:0}
};
let s={enabled:true,preset:"normal",hotkey:"KeyP",custom:{brightness:1,contrast:1,saturation:1,hue:0,sepia:0,grayscale:0}};
try{s={...s,...JSON.parse(localStorage.getItem(KEY)||"{}")};s.custom={...s.custom,...(JSON.parse(localStorage.getItem(KEY)||"{}").custom||{})}}catch{}
const root=document.createElement("div");root.id="sonnet-screen-filters";root.innerHTML=`<div id="sf-panel"><b>Screen Filters</b><button id="sf-x">×</button><div id="sf-presets"></div><hr><label>Brightness <input id="sf-b" type="range" min=".4" max="2" step=".01"></label><label>Contrast <input id="sf-c" type="range" min=".4" max="2" step=".01"></label><label>Saturation <input id="sf-s" type="range" min="0" max="2.5" step=".01"></label><label>Hue <input id="sf-h" type="range" min="-180" max="180"></label><label>Sepia <input id="sf-se" type="range" min="0" max="1" step=".01"></label><label>Grayscale <input id="sf-g" type="range" min="0" max="1" step=".01"></label><button id="sf-custom">Use Custom</button><small>F7: settings · P: cycle</small></div>`;document.documentElement.append(root);
const st=document.createElement("style");st.textContent=`#sonnet-screen-filters{position:fixed;inset:0;z-index:2147483640;pointer-events:none;font-family:Arial,sans-serif}#sf-panel{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%) scale(.96);width:min(390px,88vw);padding:16px;border:1px solid #00cfff;background:rgba(4,8,20,.96);border-radius:15px;color:#fff;box-shadow:0 0 35px #00cfff44;opacity:0;visibility:hidden;pointer-events:none;transition:.2s}#sonnet-screen-filters.open #sf-panel{opacity:1;visibility:visible;pointer-events:auto;transform:translate(-50%,-50%) scale(1)}#sf-panel>b{color:#00cfff;font-size:16px}#sf-x{float:right;background:none;border:0;color:#fff;font-size:20px}#sf-presets{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:14px 0}#sf-panel button{border:1px solid #00cfff55;border-radius:7px;padding:7px;color:#fff;background:#00cfff12;cursor:pointer}#sf-panel button.active{background:#00cfff44}#sf-panel label{display:flex;justify-content:space-between;gap:10px;margin:9px 0;font-size:12px;color:#ccd}#sf-panel input[type=range]{width:190px}#sf-panel small{display:block;margin-top:10px;color:#8ca0ad}`;document.head.append(st);
const $=q=>root.querySelector(q),save=()=>localStorage.setItem(KEY,JSON.stringify(s));
Object.entries(presets).forEach(([k,p])=>{let b=document.createElement("button");b.textContent=p.name;b.dataset.preset=k;b.onclick=()=>{s.preset=k;save();apply()};$("#sf-presets").append(b)});
$("#sf-x").onclick=()=>root.classList.remove("open");$("#sf-custom").onclick=()=>{s.preset="custom";save();apply()};
const map={"#sf-b":"brightness","#sf-c":"contrast","#sf-s":"saturation","#sf-h":"hue","#sf-se":"sepia","#sf-g":"grayscale"};Object.entries(map).forEach(([q,k])=>$(q).oninput=e=>{s.custom[k]=+e.target.value;s.preset="custom";save();apply()});
function canvas(){return [...document.querySelectorAll("canvas")].filter(x=>x.width>200&&x.height>150).sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0]}
function apply(){let v=s.preset==="custom"?s.custom:(presets[s.preset]||presets.normal),c=canvas();if(c)c.style.filter=s.enabled?`brightness(${v.brightness}) contrast(${v.contrast}) saturate(${v.saturation}) hue-rotate(${v.hue}deg) sepia(${v.sepia}) grayscale(${v.grayscale})`:"none";["b","c","s","h","se","g"].forEach((x,i)=>$("#sf-"+x).value=[v.brightness,v.contrast,v.saturation,v.hue,v.sepia,v.grayscale][i]);root.querySelectorAll("#sf-presets button").forEach(b=>b.classList.toggle("active",b.dataset.preset===s.preset))}
function key(e){if(e.repeat||["INPUT","SELECT","TEXTAREA"].includes(document.activeElement?.tagName))return;if(e.code==="F7")root.classList.toggle("open");if(e.code===s.hotkey){let a=["normal","night","dramatic","vivid","custom"],i=a.indexOf(s.preset);s.preset=a[(i+1)%a.length];save();apply()}}document.addEventListener("keydown",key,true);const timer=setInterval(apply,1000);function destroy(){document.removeEventListener("keydown",key,true);clearInterval(timer);let c=canvas();if(c)c.style.filter="";root.remove();st.remove()}window.__SonnetScreenFilters={state:s,presets,setPreset:k=>{s.preset=k;save();apply()},open:()=>root.classList.add("open"),close:()=>root.classList.remove("open"),toggle:()=>root.classList.toggle("open"),apply,destroy};apply();
})();